// <auto-generated />
using LeoClassroom.Persistence.Util;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeoClassroom.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260614055750_EventConsumers")]
    partial class EventConsumers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("leo_classroom")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssignmentUser", b =>
                {
                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("CoTeachersId")
                        .HasColumnType("bigint");

                    b.HasKey("AssignmentId", "CoTeachersId");

                    b.HasIndex("CoTeachersId");

                    b.ToTable("AssignmentTeacher", "leo_classroom");
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.Property<long>("CoTeachersId")
                        .HasColumnType("bigint");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.HasKey("CoTeachersId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseTeacher", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Acceptance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FeedbackPrNumber")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("FeedbackReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("None");

                    b.Property<Instant?>("LastCommitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("LastPushAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Late")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("LateSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepoOwner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Late");

                    b.HasIndex("StudentId");

                    b.HasIndex("AssignmentId", "StudentId")
                        .IsUnique();

                    b.ToTable("Acceptance", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchivePath")
                        .HasColumnType("text");

                    b.Property<bool>("AutoDeleteEnabled")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("AutoDeleteOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeadlineKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DownloadSnapshotMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HardDeadlineRevokesRead")
                        .HasColumnType("boolean");

                    b.Property<string>("HintsInstructions")
                        .HasColumnType("text");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReadmeMarkdown")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StarterRepoUrl")
                        .HasColumnType("text");

                    b.Property<string>("StarterSourceKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CourseId", "Slug")
                        .IsUnique();

                    b.ToTable("Assignment", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorRoles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorStudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetId")
                        .HasColumnType("text");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ActorStudentId");

                    b.HasIndex("At");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("AuditEvent", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ForgejoOrg")
                        .HasColumnType("text");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("RosterId")
                        .HasColumnType("bigint");

                    b.Property<bool>("StudentsRetainAccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RosterId", "Title");

                    b.ToTable("Course", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Roster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassKey")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassKey")
                        .IsUnique()
                        .HasFilter("\"ClassKey\" IS NOT NULL");

                    b.HasIndex("OwnerId");

                    b.ToTable("Roster", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant?>("LdapLastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("User", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.WebhookEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .HasColumnType("text");

                    b.Property<Instant?>("CommitterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepoName")
                        .HasColumnType("text");

                    b.Property<string>("RepoOwner")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("RepoOwner", "RepoName");

                    b.ToTable("WebhookEvent", "leo_classroom");
                });

            modelBuilder.Entity("RosterUser", b =>
                {
                    b.Property<long>("MembersId")
                        .HasColumnType("bigint");

                    b.Property<long>("RostersId")
                        .HasColumnType("bigint");

                    b.HasKey("MembersId", "RostersId");

                    b.HasIndex("RostersId");

                    b.ToTable("RosterUser", "leo_classroom");
                });

            modelBuilder.Entity("AssignmentUser", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.User", null)
                        .WithMany()
                        .HasForeignKey("CoTeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.User", null)
                        .WithMany()
                        .HasForeignKey("CoTeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Acceptance", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.Assignment", "Assignment")
                        .WithMany("Acceptances")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("LeoClassroom.Persistence.Model.CommitAnalytics", "Analytics", b1 =>
                        {
                            b1.Property<long>("AcceptanceId")
                                .HasColumnType("bigint");

                            b1.Property<int>("ActiveDayCount")
                                .HasColumnType("integer");

                            b1.Property<int>("CommitCount")
                                .HasColumnType("integer");

                            b1.Property<Instant?>("FirstPushAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Instant?>("LastPushAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastPushHeadSha")
                                .HasColumnType("text");

                            b1.Property<int>("PushCount")
                                .HasColumnType("integer");

                            b1.HasKey("AcceptanceId");

                            b1.ToTable("Acceptance", "leo_classroom");

                            b1.WithOwner()
                                .HasForeignKey("AcceptanceId");
                        });

                    b.Navigation("Analytics")
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Assignment", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Course", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.Roster", "Roster")
                        .WithMany()
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Roster", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RosterUser", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.Roster", null)
                        .WithMany()
                        .HasForeignKey("RostersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Assignment", b =>
                {
                    b.Navigation("Acceptances");
                });
#pragma warning restore 612, 618
        }
    }
}
