// <auto-generated />
using LeoClassroom.Persistence.Util;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeoClassroom.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("leo_classroom")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssignmentUser", b =>
                {
                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("CoTeachersId")
                        .HasColumnType("bigint");

                    b.HasKey("AssignmentId", "CoTeachersId");

                    b.HasIndex("CoTeachersId");

                    b.ToTable("AssignmentTeacher", "leo_classroom");
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.Property<long>("CoTeachersId")
                        .HasColumnType("bigint");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.HasKey("CoTeachersId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseTeacher", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Acceptance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FeedbackPrNumber")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("FeedbackReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("None");

                    b.Property<Instant?>("LastCommitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("LastPushAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Late")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("LateSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepoOwner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Late");

                    b.HasIndex("StudentId");

                    b.HasIndex("AssignmentId", "StudentId")
                        .IsUnique();

                    b.ToTable("Acceptance", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchivePath")
                        .HasColumnType("text");

                    b.Property<bool>("AutoDeleteEnabled")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("AutoDeleteOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeadlineKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DownloadSnapshotMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HardDeadlineRevokesRead")
                        .HasColumnType("boolean");

                    b.Property<string>("HintsInstructions")
                        .HasColumnType("text");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReadmeMarkdown")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StarterRepoUrl")
                        .HasColumnType("text");

                    b.Property<string>("StarterSourceKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CourseId", "Slug")
                        .IsUnique();

                    b.ToTable("Assignment", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorRoles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorStudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetId")
                        .HasColumnType("text");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ActorStudentId");

                    b.HasIndex("At");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("AuditEvent", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ForgejoOrg")
                        .HasColumnType("text");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("RosterId")
                        .HasColumnType("bigint");

                    b.Property<bool>("StudentsRetainAccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RosterId", "Title");

                    b.ToTable("Course", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.DownloadJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArtifactPath")
                        .HasColumnType("text");

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Instant?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RequestedByStudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("DownloadJob", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.MoodleItemMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("MoodleItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.ToTable("MoodleItemMapping", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.MoodleLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MoodleBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MoodleCourseId")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenCipher")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("MoodleLink", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.MoodleSyncOp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<Instant>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("MoodleSyncOp", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("AssignmentTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<Instant>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RecipientUserId")
                        .HasColumnType("bigint");

                    b.Property<Instant?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("EventKey", "RecipientUserId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("Notification", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.NotificationPreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("DeadlineChanged")
                        .HasColumnType("boolean");

                    b.Property<bool>("NewAssignment")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationPreference", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Roster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassKey")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassKey")
                        .IsUnique()
                        .HasFilter("\"ClassKey\" IS NOT NULL");

                    b.HasIndex("OwnerId");

                    b.ToTable("Roster", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant?>("GitCredentialIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant?>("LdapLastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("User", "leo_classroom");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.WebhookEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .HasColumnType("text");

                    b.Property<Instant?>("CommitterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepoName")
                        .HasColumnType("text");

                    b.Property<string>("RepoOwner")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("RepoOwner", "RepoName");

                    b.ToTable("WebhookEvent", "leo_classroom");
                });

            modelBuilder.Entity("RosterUser", b =>
                {
                    b.Property<long>("MembersId")
                        .HasColumnType("bigint");

                    b.Property<long>("RostersId")
                        .HasColumnType("bigint");

                    b.HasKey("MembersId", "RostersId");

                    b.HasIndex("RostersId");

                    b.ToTable("RosterUser", "leo_classroom");
                });

            modelBuilder.Entity("AssignmentUser", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.User", null)
                        .WithMany()
                        .HasForeignKey("CoTeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.User", null)
                        .WithMany()
                        .HasForeignKey("CoTeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Acceptance", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.Assignment", "Assignment")
                        .WithMany("Acceptances")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("LeoClassroom.Persistence.Model.CommitAnalytics", "Analytics", b1 =>
                        {
                            b1.Property<long>("AcceptanceId")
                                .HasColumnType("bigint");

                            b1.Property<int>("ActiveDayCount")
                                .HasColumnType("integer");

                            b1.Property<int>("CommitCount")
                                .HasColumnType("integer");

                            b1.Property<Instant?>("FirstPushAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Instant?>("LastPushAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("LastPushHeadSha")
                                .HasColumnType("text");

                            b1.Property<int>("PushCount")
                                .HasColumnType("integer");

                            b1.HasKey("AcceptanceId");

                            b1.ToTable("Acceptance", "leo_classroom");

                            b1.WithOwner()
                                .HasForeignKey("AcceptanceId");
                        });

                    b.Navigation("Analytics")
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Assignment", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Course", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.Roster", "Roster")
                        .WithMany()
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.MoodleLink", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Notification", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.NotificationPreference", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Roster", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RosterUser", b =>
                {
                    b.HasOne("LeoClassroom.Persistence.Model.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeoClassroom.Persistence.Model.Roster", null)
                        .WithMany()
                        .HasForeignKey("RostersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeoClassroom.Persistence.Model.Assignment", b =>
                {
                    b.Navigation("Acceptances");
                });
#pragma warning restore 612, 618
        }
    }
}
